[nit] add link colors to pdf (#90)
* [nit] add link colors to pdf

* switch to pdftk to ensure links remain after uniting

* switch to qpdf to ensure links remain after uniting - looks like pdftk doesn't work

* switch to pdftk, add numbering in the background

* add back pdftk

* fix numbering count

* add back the numbering pdf

* correctly number pages

* check that the sed completed prior to continuing

* fix current page numbering

diff --git a/.github/workflows/generate-pdf.yml b/.github/workflows/generate-pdf.yml
--- a/.github/workflows/generate-pdf.yml
+++ b/.github/workflows/generate-pdf.yml
@@ -16,8 +16,10 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Install Pandoc, Latex necessities
-        run: sudo apt-get install -y pandoc texlive texlive-latex-extra poppler-utils texlive-extra-utils
+      - name: Install Pandoc, Latex necessities, and pdftk
+        run: |
+          sudo apt-get install -y pandoc texlive texlive-latex-extra poppler-utils texlive-extra-utils pdftk
+
       - name: Install Python
         uses: actions/setup-python@v4
         with:
@@ -76,14 +78,15 @@ jobs:
           )
           for md_file in "${file_list[@]}"; do
             pdf_file_name="pdf_output/$(echo "$md_file" | sed 's/\//_/g' | sed 's/.md//g').pdf"
-            python3 generate-pdf-edits.py "$md_file" | pandoc -V geometry:margin=1in --pdf-engine=pdflatex -o "$pdf_file_name"
+            python3 pdf-generation/generate-pdf-edits.py "$md_file" | pandoc -V geometry:margin=1in -V colorlinks=true -V linkcolor=blue -V urlcolor=blue --pdf-engine=pdflatex -o "$pdf_file_name"
 
             if [ ! -f "$pdf_file_name" ]; then
               echo "Error: PDF file $pdf_file_name not created!" >&2
               exit 1
             fi
           done
-          pdfunite \
+
+          pdftk \
             "pdf_output/index.pdf" \
             "pdf_output/principles_index.pdf" \
             "pdf_output/principles_principles.pdf" \
@@ -129,14 +132,34 @@ jobs:
             "pdf_output/network_abusing-intrusion-detection.pdf" \
             "pdf_output/network_malware.pdf" \
             "pdf_output/network_tor.pdf" \
-            "textbook_full.pdf"
+            cat output "textbook_full_original.pdf"
       
       - name: Inject page numbers back into the pdf
-        run: pdfjam --pagecommand '\pagestyle{plain}' --outfile textbook_full.pdf textbook_full.pdf
+        run: |
+          mkdir -p pdf_numbering_output
+
+          num_pages=$(pdftk textbook_full_original.pdf dump_data | grep NumberOfPages | awk '{print $2}')
+          sed -i "s/194/$num_pages/" pdf-generation/numbering.tex
+          
+          # Don't continue if the sed failed
+          if [ $? -ne 0 ]; then
+            echo "Error: sed command failed" >&2
+            exit 1
+          fi
+
+          pdflatex pdf-generation/numbering.tex
+          pdftk pdf-generation/numbering.pdf burst output pdf_numbering_output/number_%03d.pdf
+          pdftk textbook_full_original.pdf burst output pdf_numbering_output/page_%03d.pdf
+          for i in $(seq -f %03g 1 $num_pages) ; do pdftk pdf_numbering_output/page_$i.pdf background pdf_numbering_output/number_$i.pdf output pdf_numbering_output/new_$i.pdf; done
+
+          pdftk pdf_numbering_output/new_???.pdf output textbook_full.pdf
+
+          sed -i "s/$num_pages/194/" pdf-generation/numbering.tex
 
       - name: Remove temporary files, make temporary copy to upload as artifact
         run: |
           rm -rf pdf_output
+          rm -rf pdf_numbering_output
           cp textbook_full.pdf textbook_full_cpy.pdf
 
       - name: Upload PDF as an artifact
